name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build plugin
              run: |
                  npm install
                  npm run build

            - name: Prepare release files
              run: |
                  mkdir -p release
                  cp main.js manifest.json release/

            - name: Debug release files
              run: |
                  ls -al release

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  gh release create "$tag" \
                      --title="$tag" \
                      --draft \
                      release/main.js release/manifest.json
